### PR TITLE
EAGLE-296 Test unit for JobConfParserImpl

### PR DESCRIPTION
**Pull request by r7raul1984**
- TestJobConfParserImpl and jobconf.html to test jobconf parse.

Jira: https://issues.apache.org/jira/browse/EAGLE-296

### CODE REVIEW

**Comment by yonzhang** [comment]
This looks good!

**Comment by yonzhang** [comment]
fixed and merged https://github.com/apache/incubator-eagle/commit/5578cfd912d70ebc0bb52a754f145996c6e5efd8. Please allow 2 weeks for merging into master

**Comment by qingwen220** [comment]
have conflicts. Maybe rebase is needed

**Comment by yonzhang** [comment]
@r7raul1984 why this is re-opened please manually close this pull request, this has been merged in another PR.

**Pull request closed without merging**
