### PR TITLE
EAGLE-339: Automatically create hbase table when initializing

### PR DESCRIPTION
**Pull request by qingwen220**
https://issues.apache.org/jira/browse/EAGLE-339

### CODE REVIEW

**Comment by qingwen220** [comment]
all tests are passed in the local environment with java 1.7

**Comment by yonzhang** [comment]
for RDBMS, do we automatically create tables?

**Comment by anyway1021** [comment]
Yes, for RDBMS, after the service is up, it will create tables automatically. This functionality has been fully tested.

**Comment by qingwen220** [comment]
This pull request is to make sure no matter what the database is, starting Eagle service has a same procedure.

**Comment by yonzhang** [comment]
Thanks please merge that

**Pull request closed without merging**
