### PR TITLE
Eagle 0.5 ingestion + alert engine preview

### PR DESCRIPTION
**Pull request by yonzhang**

### CODE REVIEW

**Comment by haoch** [comment]
Good fix. To become a high-quality project, we should at least try to make sure cleaning all compiling warning if possible.

**Comment by baibaichen** [comment]
building eagle-topology-assembly failed because eagle-security-hdfs-securitylog and eagle-security-hbase-securitylog are renamed, and eagle-security-userprofile are removed.

As a **high-quality** project,  it is better passing build before submitting.

**Comment by yonzhang** [comment]
Sorry about that, this change impacts develop branch only, 0.4 branch is stable brach and soon be out.
I am checking develop branch to make sure it passes build.
By the way, develop branch has many changes regarding code structure because of introducing new alert engine and metadata change, to build successfully with develop branch, it is better to clean your local repo one time

**Comment by yonzhang** [comment]
it is fixed now, sorry again for the inconvenience.

**Comment by baibaichen** [comment]
Thanks for response!

Would you please give me some backgrounds(or link) about   new alter engine?

**Comment by yonzhang** [comment]
Sure, will get back to you soon!

**Comment by yonzhang** [comment]
@baibaichen can you send to me your email, I can respond to you the background of new alert engine, today we don't have design doc ready, and that will be announced 4 weeks later . My email is yonzhang2012@apache.org

**Pull request closed without merging**
