### PR TITLE
Eagle-447 convert eagle-maprfs app to use new app framework

### PR DESCRIPTION
**Pull request by DadanielZ**
eagle-maprfs app should use new app framework to manage its lifecycle

### CODE REVIEW

**Comment by yonzhang** [comment]
Thanks for the improvement. Why we create a new AbstractMapRFSAuditLogApplication, can't we use AbstractHdfsAuditLogApplication? They share the same code

**Comment by haoch** [comment]
ApplicationProvider and XML metadata descriptor is missing.

**Comment by haoch** [comment]
Pls. refer to :
* Metadata descriptor and SPI: https://github.com/apache/incubator-eagle/tree/develop/eagle-security/eagle-security-hdfs-auditlog/src/main/resources/META-INF
* ApplicationProvider: https://github.com/apache/incubator-eagle/blob/develop/eagle-security/eagle-security-hdfs-auditlog/src/main/java/org/apache/eagle/security/auditlog/HdfsAuditLogAppProvider.java
* Better to have Unit Test to make sure all set: https://github.com/apache/incubator-eagle/blob/develop/eagle-jpm/eagle-jpm-spark-running/src/test/java/SparkRunningJobAppProviderTest.java#L30

**Comment by DadanielZ** [comment]
@yonzhang Their code are almost the  same except that: "AbstractHdfsAuditLogApplication" use "HdfsAuditLogParserBolt", "AbstractMapRFSAuditLogApplication" should use "MapRFSAuditLogParserBolt".

**Comment by DadanielZ** [comment]
@haoch thanks for the review, will add them later.

**Comment by yonzhang** [comment]
@DadanielZ that is why there is already AbstractHdfsAuditLogApplication there, and MapRApplication can extend this and implement getParserBolt method

**Comment by DadanielZ** [comment]
@yonzhang, I see now. In “ AbstractHdfsAuditLogApplication.java”, there is an overrided function which use "HdfsAuditLogParserBolt" directly:
```
@Override
public StormTopology execute(Config config, StormEnvironment environment){
...
HdfsAuditLogParserBolt parserBolt = new HdfsAuditLogParserBolt();
BoltDeclarer boltDeclarer = builder.setBolt("parserBolt", parserBolt, numOfParserTasks);
...
}
```
that's why I wrote "AbstractMapRFSAuditLogApplication" and call "MapRFSAuditLogParserBolt".

I think I should refactor the code in "AbstractHdfsAuditLogApplication" and let it call "getParserBolt"  to get parserBolt, then extend this class for mapr application:
```
@Override
public StormTopology execute(Config config, StormEnvironment environment){
...
BaseRichBolt parserBolt = getParserBolt();
BoltDeclarer boltDeclarer = builder.setBolt("parserBolt", parserBolt, numOfParserTasks);
...
}
```
Will fix it.

**Pull request closed without merging**
