### PR TITLE
EAGLE-298 Oozie auditlog integration for Oozie security monitoring

### PR DESCRIPTION
**Pull request by r7raul1984**
- Add oozie auditlog parse code and related test code.
- Add job.html and controll.js code for new view type job.
- Add oozie auditlog entity ,oozie metatdata access config code and related test code.

https://issues.apache.org/jira/browse/EAGLE-298

### CODE REVIEW

**Comment by haoch** [comment]
LGTM.

**Comment by haoch** [comment]
@yonzhang have you reviewed the PR detail? If you still have problem about manual PR patch applying, please try the PR tools under [eagle-dev](https://github.com/apache/incubator-eagle/tree/master/eagle-dev)? If you are ok with the code change, please help merge the PR.

**Comment by r7raul1984** [comment]
@haoch What I need to do next?

**Comment by haoch** [comment]
@r7raul1984 no need, thanks very much for the contribution 👍 and welcome to join eagle community!

**Comment by haoch** [comment]
The patch has been merged into https://github.com/apache/incubator-eagle/commit/fd39e6e14ed5cdca1e7b4314b2b4e5e1d1d97425, please close the pull request.

**Comment by r7raul1984** [comment]
Thank you !

**Pull request closed without merging**
