### PR TITLE
EAGLE-404: Updating configuration format check at the front end

### PR DESCRIPTION
**Pull request by qingwen220**
https://issues.apache.org/jira/browse/EAGLE-404

### CODE REVIEW

**Comment by zombieJ** [comment]
LGTM
ps: Is there any other name format should be considered? Or that's OK

**Comment by qingwen220** [comment]
I don't know other cases right now.  

At present, the combination of letters(a-z or A-Z), digits and dot are not enough. '-' is a must to have. 

For example, hdfs ha configuration

dfs.namenode.rpc-address.xxx=yyy

**Comment by yonzhang** [comment]
this PR is for 0.4, but 0.4 is already cut, do you want to submit another PR for develop branch?

**Comment by qingwen220** [comment]
@yonzhang  this fix is only for v0.4.

**Comment by yonzhang** [comment]
ok, thanks, please merge it soon

**Comment by haoch** [comment]
Merged, pls. close it.

**Pull request closed without merging**
