### PR TITLE
EAGLE-47 Ability to audit who made changes to Eagle policies

### PR DESCRIPTION
**Pull request by murkrishn**
Code change includes implementation of audit functionality. Documentation of the generic API design for the same is available [here](https://github.com/apache/incubator-eagle/files/71519/eagle_47_generic_audit_api_design.pdf).

### CODE REVIEW

**Comment by yonzhang** [comment]
One comment: why do we need named audit listener? I see HBaseStorageAudit.isAuditingRequired checks if the passed service name matches "AlertDefinitionService" or "AlertDataSourceService".

**Comment by murkrishn** [comment]
For the particular implementation in HBaseStorageAudit, we would be auditing the HBase operations only for the services - AlertDefinitionService and AlertDataSourceService provided the auditing option is  also enabled . Having named registering of implementation will help us to include/remove another implementation if required.

**Comment by yonzhang** [comment]
understood, please go ahead to merge

**Comment by anyway1021** [comment]
@yonzhang , if we're going to run the script and merge, PRs need an approval comment on the page. The approval comment should contain a single line with a string, either ":+1:", or "LGTM", we can regard these 2 string as approval marks.

Please take notice, the marks should take 1 single line with no other messages, just like below:

:+1: 

or

LGTM

Then, when you execute the merge script, it will verify and know that this PR is reviewed and approved to be merged.

**Comment by yonzhang** [comment]
:+1:

**Pull request closed without merging**
