### PR TITLE
EAGLE-239 UI Fix alert detail context

### PR DESCRIPTION
**Pull request by zombieJ**
Alert entity use alertContext directly instead of alertContext.properties. Which sync update with UI.

### CODE REVIEW

**Comment by haoch** [comment]
1. Change "Data Source" to "Application"
2. Alert List view is still almost empty with "Alert Time" only.

**Comment by qingwen220** [comment]
This pr may conflict with the entity model, as I have recovered the AlertAPIEntity. alertContext.properties remain here. 

You can check the newest code

**Comment by haoch** [comment]
Could you please paste the previous and current sample alert json content here?

**Comment by qingwen220** [comment]
**Previous**
```
{  
   "timestamp":1460542328725,
   "tags":{  
      "site":"sandbox",
      "alertSource":"30139@sandbox.hortonworks.com",
      "application":"hdfsAuditLog",
      "sourceStreams":"hdfsAuditLogEventStream",
      "policyId":"testHDFS",
      "alertExecutorId":"hdfsAuditLogAlertExecutor"
   },
   "alertContext":"{\"site\":\"sandbox\",\"allowed\":\"true\",\"application\":\"hdfsAuditLog\",\"host\":\"10.115.59.58\",\"policyDetailUrl\":\"http://localhost:9099/eagle-service/#/dam/policyDetail?policy=testHDFS&site=sandbox&executor=hdfsAuditLogAlertExecutor\",\"securityZone\":\"NA\",\"dst\":\"NA\",\"alertMessage\":\"The Policy \\\"testHDFS\\\" has been detected with the below information: timestamp=\\\"1438307675161\\\" allowed=\\\"true\\\" cmd=\\\"open\\\" host=\\\"10.115.59.58\\\" sensitivityType=\\\"NA\\\" securityZone=\\\"NA\\\" src=\\\"/tmp/private\\\" dst=\\\"NA\\\" user=\\\"b_pcatalogs\\\" \",\"alertEvent\":\"timestamp=\\\"1438307675161\\\" allowed=\\\"true\\\" cmd=\\\"open\\\" host=\\\"10.115.59.58\\\" sensitivityType=\\\"NA\\\" securityZone=\\\"NA\\\" src=\\\"/tmp/private\\\" dst=\\\"NA\\\" user=\\\"b_pcatalogs\\\" \",\"alertTimestamp\":\"2016-04-13 10:12:08\",\"timestamp\":\"1438307675161\",\"cmd\":\"open\",\"alertDetailUrl\":\"http://localhost:9099/eagle-service/#/dam/alertDetail/tv4MJX%5F%5F%5Fqvw5LBqlXeMWIuAAAjHMWiXlB00YOsfe8qEr9wdADXfR28vvscgmSntu59uW1ykBVB3iZNS\",\"sourceStreams\":\"hdfsAuditLogEventStream\",\"sensitivityType\":\"NA\",\"policyId\":\"testHDFS\",\"src\":\"/tmp/private\",\"user\":\"b_pcatalogs\"}"
   "serializeVerbose":true
}
```

**Current**
```
{  
   "timestamp":1460542328725,
   "tags":{  
      "site":"sandbox",
      "alertSource":"30139@sandbox.hortonworks.com",
      "application":"hdfsAuditLog",
      "sourceStreams":"hdfsAuditLogEventStream",
      "policyId":"testHDFS",
      "alertExecutorId":"hdfsAuditLogAlertExecutor"
   },
   "alertContext":{  
      "properties":{  
         "allowed":"true",
         "site":"sandbox",
         "application":"hdfsAuditLog",
         "host":"10.115.59.58",
         "policyDetailUrl":"http://localhost:9099/eagle-service/#/dam/policyDetail?policy=testHDFS&site=sandbox&executor=hdfsAuditLogAlertExecutor",
         "securityZone":"NA",
         "dst":"NA",
         "alertMessage":"The Policy \"testHDFS\" has been detected with the below information: timestamp=\"1438307675161\" allowed=\"true\" cmd=\"open\" host=\"10.115.59.58\" sensitivityType=\"NA\" securityZone=\"NA\" src=\"/tmp/private\" dst=\"NA\" user=\"b_pcatalogs\" ",
         "alertEvent":"timestamp=\"1438307675161\" allowed=\"true\" cmd=\"open\" host=\"10.115.59.58\" sensitivityType=\"NA\" securityZone=\"NA\" src=\"/tmp/private\" dst=\"NA\" user=\"b_pcatalogs\" ",
         "timestamp":"1438307675161",
         "alertTimestamp":"2016-04-13 10:12:08",
         "cmd":"open",
         "alertDetailUrl":"http://localhost:9099/eagle-service/#/dam/alertDetail/tv4MJX%5F%5F%5Fqvw5LBqlXeMWIuAAAjHMWiXlB00YOsfe8qEr9wdADXfR28vvscgmSntu59uW1ykBVB3iZNS",
         "sourceStreams":"hdfsAuditLogEventStream",
         "policyId":"testHDFS",
         "sensitivityType":"NA",
         "src":"/tmp/private",
         "user":"b_pcatalogs"
      }
   }
}

```

**Comment by qingwen220** [comment]
**Before** 
```
{  
   "timestamp":1460542328725,
   "tags":{  
      "site":"sandbox",
      "alertSource":"30139@sandbox.hortonworks.com",
      "application":"hdfsAuditLog",
      "sourceStreams":"hdfsAuditLogEventStream",
      "policyId":"testHDFS",
      "alertExecutorId":"hdfsAuditLogAlertExecutor"
   },
   "alertContext":"{\"site\":\"sandbox\",\"allowed\":\"true\",\"application\":\"hdfsAuditLog\",\"host\":\"10.0.0.1\",\"policyDetailUrl\":\"http://localhost:9099/eagle-service/#/dam/policyDetail?policy=testHDFS&site=sandbox&executor=hdfsAuditLogAlertExecutor\",\"securityZone\":\"NA\",\"dst\":\"NA\",\"alertMessage\":\"The Policy \\\"testHDFS\\\" has been detected with the below information: timestamp=\\\"1438307675161\\\" allowed=\\\"true\\\" cmd=\\\"open\\\" host=\\\"10.0.0.1\\\" sensitivityType=\\\"NA\\\" securityZone=\\\"NA\\\" src=\\\"/tmp/private\\\" dst=\\\"NA\\\" user=\\\"userA\\\" \",\"alertEvent\":\"timestamp=\\\"1438307675161\\\" allowed=\\\"true\\\" cmd=\\\"open\\\" host=\\\"10.0.0.1\\\" sensitivityType=\\\"NA\\\" securityZone=\\\"NA\\\" src=\\\"/tmp/private\\\" dst=\\\"NA\\\" user=\\\"userA\\\" \",\"alertTimestamp\":\"2016-04-13 10:12:08\",\"timestamp\":\"1438307675161\",\"cmd\":\"open\",\"alertDetailUrl\":\"http://localhost:9099/eagle-service/#/dam/alertDetail/tv4MJX%5F%5F%5Fqvw5LBqlXeMWIuAAAjHMWiXlB00YOsfe8qEr9wdADXfR28vvscgmSntu59uW1ykBVB3iZNS\",\"sourceStreams\":\"hdfsAuditLogEventStream\",\"sensitivityType\":\"NA\",\"policyId\":\"testHDFS\",\"src\":\"/tmp/private\",\"user\":\"userA\"}",
   "serializeVerbose":true
}
```
**Current**
```
{  
   "timestamp":1460542328725,
   "tags":{  
      "site":"sandbox",
      "alertSource":"30139@sandbox.hortonworks.com",
      "application":"hdfsAuditLog",
      "sourceStreams":"hdfsAuditLogEventStream",
      "policyId":"testHDFS",
      "alertExecutorId":"hdfsAuditLogAlertExecutor"
   },
   "alertContext":{  
      "properties":{  
         "allowed":"true",
         "site":"sandbox",
         "application":"hdfsAuditLog",
         "host":"10.0.0.1",
         "policyDetailUrl":"http://localhost:9099/eagle-service/#/dam/policyDetail?policy=testHDFS&site=sandbox&executor=hdfsAuditLogAlertExecutor",
         "securityZone":"NA",
         "dst":"NA",
         "alertMessage":"The Policy \"testHDFS\" has been detected with the below information: timestamp=\"1438307675161\" allowed=\"true\" cmd=\"open\" host=\"10.0.0.1\" sensitivityType=\"NA\" securityZone=\"NA\" src=\"/tmp/private\" dst=\"NA\" user=\"userA\" ",
         "alertEvent":"timestamp=\"1438307675161\" allowed=\"true\" cmd=\"open\" host=\"10.0.0.1\" sensitivityType=\"NA\" securityZone=\"NA\" src=\"/tmp/private\" dst=\"NA\" user=\"userA\" ",
         "timestamp":"1438307675161",
         "alertTimestamp":"2016-04-13 10:12:08",
         "cmd":"open",
         "alertDetailUrl":"http://localhost:9099/eagle-service/#/dam/alertDetail/tv4MJX%5F%5F%5Fqvw5LBqlXeMWIuAAAjHMWiXlB00YOsfe8qEr9wdADXfR28vvscgmSntu59uW1ykBVB3iZNS",
         "sourceStreams":"hdfsAuditLogEventStream",
         "policyId":"testHDFS",
         "sensitivityType":"NA",
         "src":"/tmp/private",
         "user":"userA"
      }
   },
   "serializeVerbose":true
}
```

**Comment by haoch** [comment]
@zombieJ , as @qingwen220 changes the alert entity schema, could you please update the patch correspondingly?

**Comment by haoch** [comment]
LGTM

**Pull request closed without merging**
