### PR TITLE
EAGLE-86: Rewrite HDFSAuditLogParser to a non-regular expression version

### PR DESCRIPTION
**Pull request by sunlibin**

### CODE REVIEW

**Comment by RalphSu** [comment]
Looks good to me +2

**Comment by haoch** [comment]
LGTM. Only one problem: could you pls. change the pull request title as "EAGLE-86: Rewrite HDFSAuditLogParser to a non-regular expression version"?

**Comment by haoch** [comment]
We should make sure referring to ticket id `EAGLE-ID`

**Comment by sunlibin** [comment]
Thanks for reminder, added the missing hyphen

**Comment by haoch** [comment]
LGTM, please merge accordingly.

**Pull request closed without merging**
