### PR TITLE
update development-in-sandbox.md 

### PR DESCRIPTION
**Pull request by JingGe**
1. add reference for development environment setup.
2. add info to let user know how to copy the package file into sandbox.

### CODE REVIEW

**Comment by haoch** [comment]
:+1:

**Comment by haoch** [comment]
Merged into https://github.com/apache/incubator-eagle/commit/431ce9c4930ef6aab8ab090a263614633af97294, thanks for the contribution :-) Please close the ticket.

**Comment by haoch** [comment]
@JingGe could you please help close the ticket?

**Comment by pkuwm** [comment]
Reminder to close the PR.

**Pull request closed without merging**
