### PR TITLE
EAGLE-236. Change project version to "0.4.0-SNAPSHOT" since "v0.3.0" has been released.

### PR DESCRIPTION
**Pull request by pkuwm**
I replaced all "<version>0.3.0-incubating</version>" in each file with "<version>0.4.0-SNAPSHOT-incubating</version>".

### CODE REVIEW

**Comment by haoch** [comment]
Thanks for the contribution 👍 , but as more common practice, it's better to use `0.4.0-incubating-SNAPSHOT` instead of `0.4.0-SNAPSHOT-incubating` where `0.4.0-incubating` is the target version and postfix "-SNAPSHOT" stands for temporary status which maybe removed after released :-)

**Comment by pkuwm** [comment]
OK. Will change it right now.

**Comment by pkuwm** [comment]
Done. Can someone review it? Thanks.

**Comment by pkuwm** [comment]
Merged.

**Pull request closed without merging**
