### PR TITLE
EAGLE-298 Oozie auditlog integration for Oozie security monitoring

### PR DESCRIPTION
**Pull request by r7raul1984**
- Add oozie auditlog parse code and related test code.
- Add job.html and controll.js code for new view type job.
- Add oozie auditlog entity ,oozie metatdata access config code and related test code.

https://issues.apache.org/jira/browse/EAGLE-298

### CODE REVIEW

**Comment by yonzhang** [comment]
I applied this patch in  my local, there is some issue.  I would suggest you rebase your local branch and do commit squash and then create PR.

error: eagle-core/eagle-data-process/eagle-storm-jobrunning-spout/src/test/java/org/apache/eagle/jobrunning/job/conf/TestJobConfParserImpl.java: already exists in working directory
error: eagle-core/eagle-data-process/eagle-storm-jobrunning-spout/src/test/resources/jobconf.html: already exists in working directory
error: patch failed: eagle-security/eagle-security-common/src/test/java/org/apache/eagle/security/crawler/audit/TestMetaDataAccessConfigRepo.java:51
error: eagle-security/eagle-security-common/src/test/java/org/apache/eagle/security/crawler/audit/TestMetaDataAccessConfigRepo.java: patch does not apply
error: patch failed: eagle-topology-assembly/pom.xml:87
error: eagle-topology-assembly/pom.xml: patch does not apply

**Comment by yonzhang** [comment]
Another issue: can we revert configuration change for tomcat server.xml?

**Comment by r7raul1984** [comment]
Should close this PR?

**Comment by yonzhang** [comment]
yes  please close it pr，fix and create a new

**Comment by haoch** [comment]
@yonzhang could you please have a try with [eagle-dev/merge-eagle-pr.py](https://github.com/apache/incubator-eagle/blob/master/eagle-dev/merge-eagle-pr.py) to merge test-passed but conflict pr?

**Pull request closed without merging**
