### PR TITLE
[EAGLE-422] eagle support for mr & spark running job monitoring

### PR DESCRIPTION
**Pull request by wujinhu**

### CODE REVIEW

**Comment by wujinhu** [comment]
https://issues.apache.org/jira/browse/EAGLE-422

**Comment by qingwen220** [comment]
LGTM

**Comment by wujinhu** [comment]
I have removed the sensitive information and update the code

**Comment by qingwen220** [comment]
testApplicationDescWrapperConfigLoadFromXML failed in Jenkins. While unit tests all passed in local

**Pull request closed without merging**
