### PR TITLE
EAGLE-652 : get valid hostname for datanode

### PR DESCRIPTION
**Pull request by puyulu**
https://issues.apache.org/jira/browse/EAGLE-652

### CODE REVIEW

**Comment by haoch** [comment]
Before move on to merge the PR, could you please clean up the changes? Why `+566`  changes?

**Comment by haoch** [comment]
What's the relationship of this ticket with #546 ?

**Comment by haoch** [comment]
@puyulu please close this PR

**Comment by puyulu** [comment]
fixed it

**Pull request closed without merging**
