### PR TITLE
EAGLE-84 create first version of auto_merge.py under folder eagle-dev

### PR DESCRIPTION
**Pull request by anyway1021**
This version doesn't include the logic of checking unit test results reported by CI jobs. The purposes of this pull request are:
1. create sub-directory of "eagle-dev" in the project's root directory to contain dev related tools or scripts.
2. contribute this first version so that people can use it instead of manually scripting jobs to merge, edit, commit and push.
3. let this script receive widely review.

The integration of Github & CI is under way, and I will update this script once I'm aware enough of the verification logic for unit test results, soon.

Any code review and suggestion will be appreciated.

### CODE REVIEW

**Comment by anyway1021** [comment]
This is a copy of an experimentation execution log of the script, which is hoped to help reviewers (git-repo-url, ticket-id are mocked, not apache/incubator-eagle):
-------------------- START PROCESSING --------------------
INF: query pr information from github...
INF: will use "am_eagle_remote" as a remote name to operate
INF: looking up comments from github...
INF: verified: this pr is reviewed by ['anyway1021'] and finally approved by ['anyway1021'], it's good to merge
INF: querying email address for reviewers' account from github...
INF: downloading 17.patch from github...
IPT: please input the description of the merge, which will be regarded as a part of the final commit message
(<press Enter key> to start new lines, <press Ctrl+D> to finish inputting):
recover 
INF: committed to local repository on branch operating_branch_1451350746196985, the commit history now looks like: 
new -> 	* commit 643dc13d5560eae734ea1e9ac166d68adf363113 (HEAD, operating_branch_1451350746196985)
	| Author: ziwu <ziyang.wu@ebay.com>
	| Date:   Tue Dec 29 08:59:39 2015 +0800
	| 
	|     EAGLE-31 recover toString() of Address.java
	|     recover
	|     
	|     https://issues.apache.org/jira/browse/EAGLE-31
	|     
	|     Author: @anyway1021 <mchl.wu5@gmail.com>
	|     Reviewer(s): @anyway1021 <mchl.wu5@gmail.com>
	|     
	|     Closes #17.
	|  
old -> 	* commit 2a935badad668b97de7c8e8a9150786c88fabb8d (am_eagle_remote/master)
	| Author: ziwu <ziyang.wu@ebay.com>
	| Date:   Mon Dec 28 22:58:14 2015 +0800
	| 
	|     EAGLE-31 add street1 info to toString() of Address.java
	|     ddaabb
	|     
	|     https://issues.apache.org/jira/browse/EAGLE-31
	|     
	|     Author: @anyway1021 <mchl.wu5@gmail.com>
	|     Reviewer(s): @anyway1021 <mchl.wu5@gmail.com>
	|     
	|     Closes #16.
	* commit ......
IPT: shall we push commit <643dc13d5560eae734ea1e9ac166d68adf363113> to remote <am_eagle_remote/master>?
(<input "y" or "n" and press Enter key>):y
INF: pushing to remote repository...
INF: pull request <17> has been applied and pushed to remote <am_eagle_remote/master> of repository <https://github.com/anyway-checker/pr-merge-test.git>
INF: if you're going to continue with any forked repository, please update it accordingly
INF: Bye.
-------------------- ENDED PROCESSING --------------------

**Comment by haoch** [comment]
LGTM, will test for some days before merging into code base. Thanks for the contribution. @anyway1021

**Comment by haoch** [comment]
Please use python-2.7 instead of python-3.*

**Comment by haoch** [comment]
And how do you think rename to script to a more meaningful name say `merge_pull_request.py` instead of `auto_merge.py`? Because the script is actually executed manually but not automatically.

**Comment by anyway1021** [comment]
Sure, Hao, that's a good suggestion and the old name was not defined as the
final one, i'll change these things and add commits to the PR.

**Comment by haoch** [comment]
Failed to merge "https://github.com/apache/incubator-eagle/pull/51" due to `ERR: the title of the pull request should start with "EAGLE-${jira_id}", followed by a white-space and textual content, please revise accordingly, exit with code -1 ...`, maybe it possible to support give jirap-id by parameters?

**Comment by haoch** [comment]
Could we get the author email from commit patch instead of github account api?

**Comment by anyway1021** [comment]
@haoch 

The error of #51 occurs because the title of the PR is not in the expected format, it starts with "EAGLE-114:" but not "EAGLE-114", there is an additional ":"
For sure, it's possible to support passing jira-id, do you mean in this way we don't have to check the title, but instead form a correct title by the script itself? I think this is a good idea, but do we need to check the authenticity of the jira id? Please confirm.

BTW, did you mean to get author's email from the info in patch file or some other place? Actually we can get a lot of info from a pr url, but emails may vary in different places. E.g. my global git config takes company's account and email as a user, but for apache projects, I have to config the local user with github accounts, if anyone forget this, the email info in commits will be different. So, which will be better reliable?

**Comment by anyway1021** [comment]
Updates made until commit "359546f":
1. Embed debug messages when the script is executed with argument “-l debug” or “--log-level debug”, other wise, it only output “info” log.
2. Enhance the error handling and env-recovery mechanism.
3. Add non-patch mode to accomplish the goal. If the script is executed with a “-p” or “--patch” argument, it will use the patch mode, otherwise it uses non-patch mode by default.
4. Improve the compatibility for running it in windows and mac system.
5. Enrich help message for better instructions.

**Comment by haoch** [comment]
@anyway1021 thanks very much for the contribution, but it seems that the script is too complex for daily  development work. I can't succeed to process any PR until now.

**Comment by haoch** [comment]
Please close the pull request because it has been merged.

**Pull request closed without merging**
