### PR TITLE
EAGLE-516 Implement application entity service by jdbc

### PR DESCRIPTION
**Pull request by r7raul1984**
- Implement application entity service by jdbc
- Implement site entity service by jdbc
- Add query/queryWithCond/update method in JDBCMetadataQueryService

https://issues.apache.org/jira/browse/EAGLE-516

### CODE REVIEW

**Comment by haoch** [comment]
Thanks for the contribution.

**Comment by r7raul1984** [comment]
Anytime!

**Comment by haoch** [comment]
@r7raul1984 have you finished develop for this ticket?

**Comment by r7raul1984** [comment]
Yes.

**Comment by haoch** [comment]
LGTM.

**Pull request closed without merging**
