### PR TITLE
[EAGLE-502] Always retry to parse spark history job when failure happens.

### PR DESCRIPTION
**Pull request by pkuwm**

### CODE REVIEW

**Comment by pkuwm** [comment]
The jenkins check failure is due to the previous commit. Please see the console log.

**Comment by wujinhu** [comment]
It seems there is no retry logic now. Please verify the code. I think something is missing.

**Comment by pkuwm** [comment]
Thanks @wujinhu 
I have updated the code. The following code has been added.
`    @Override
    public void fail(Object msgId) {
        collector.emit(new Values(msgId), msgId);
        zkState.updateApplicationStatus((String)msgId, ZKStateConstant.AppStatus.SENT_FOR_PARSE);
    }`

**Comment by wujinhu** [comment]
Looks good to me now.  It will be better have a sleep for some seconds when you emit it.

**Comment by pkuwm** [comment]
This is a good tip to void high CPU usage on retry.
I have updated it to sleep 5 secs.

**Comment by haoch** [comment]
@pkuwm pls. resolve conflict firstly.

**Comment by pkuwm** [comment]
Conflicts resolved.

**Comment by qingwen220** [comment]
merged, please close it

**Comment by pkuwm** [comment]
Thanks.

**Pull request closed without merging**
