### PR TITLE
EAGLE-75: Integrate dropwizard metric framework

### PR DESCRIPTION
**Pull request by sunlibin**

### CODE REVIEW

**Comment by haoch** [comment]
Could you please help list a metric list in eagle wiki before we merge this pull request?

**Comment by haoch** [comment]
https://cwiki.apache.org/confluence/display/EAG

**Comment by haoch** [comment]
The pull request title is bad.

**Comment by RalphSu** [comment]
Applied patch, runs ok for me. Would like to another reviewer.

for the project name, 'eagle-security-metric-collection' seems better before we make it general.

**Comment by haoch** [comment]
Please fix the title referring to https://cwiki.apache.org/confluence/display/EAG/Contributing+to+Eagle

**Comment by sunlibin** [comment]
Added the missing hyphen of the title

**Comment by haoch** [comment]
LGTM, please merge according to https://cwiki.apache.org/confluence/display/EAG/Contributing+to+Eagle

**Comment by sunlibin** [comment]
Added metric wiki: https://cwiki.apache.org/confluence/display/EAG/Eagle+Metric+Framework

**Pull request closed without merging**
