### PR TITLE
EAGLE-458 Migrate eagle-jpm-spark-running using appplication framework

### PR DESCRIPTION
**Pull request by haoch**
https://issues.apache.org/jira/browse/EAGLE-458

### CODE REVIEW

**Comment by yonzhang** [comment]
LGTM. but to complete application conversion, we need complete configuration in metadata.xml like application.conf. Future, we may be able to reduce this duplication.

**Comment by haoch** [comment]
`metadata.xml` is part of code, `application.conf` should just for standalone running mode. We should never mix them, the `value` in `metadata.xml` just stands for `defaultValue` and should be treated as configuration file. Currently we still have to manually do it. And for some application, i may have tens of configuration items like this app. 

Better solution is make the `configuration` in `metadata.xml` be part of code as designed before like:

~~~
AppConfiguration{
     @Property(name="eagle.app.configName",displayName="ConfigName", defaultValue="defaultValue")
     public String configName;
}
~~~

It should be good for:

1. Provide metadata inline in typesafe way and avoid ugly get configuration by Config.getXXX method hidden in logic code.
2. Automatically map configuration instance from typesafe Config through annotation.

**Comment by haoch** [comment]
Added configuration descriptor for SparkRunningJobApp

**Comment by haoch** [comment]
Merged and close.

**Pull request closed without merging**
