### PR TITLE
[EAGLE-500] fix process-stopping issue of mongodb unit test case

### PR DESCRIPTION
**Pull request by anyway1021**
https://issues.apache.org/jira/browse/EAGLE-500

### CODE REVIEW

**Comment by haoch** [comment]
Could we just catch the `shutdown` exception and print logs instead of throw out? Exception message matching related condition looks lot very solid :-)

**Comment by anyway1021** [comment]
@haoch , modified it, please take a look.

**Comment by haoch** [comment]
LGTM, pls merge.

**Comment by haoch** [comment]
Merged, pls. close #387.

**Comment by anyway1021** [comment]
Thanks!

**Pull request closed without merging**
