### PR TITLE
EAGLE-276 eagle support for mr & spark history job monitoring

### PR DESCRIPTION
**Pull request by wujinhu**
add history job monitoring for eagle

### CODE REVIEW

**Comment by haoch** [comment]
Please update all module version from `0.3.0-incubating` to `0.5.0-incubating-SNAPSHOT`

**Comment by haoch** [comment]
Please pull latest code from `develop` branch and make sure building against `jdk8`.

**Comment by haoch** [comment]
Really a huge patch, could list all authors for this pull request?

**Comment by RalphSu** [comment]
For such big feature contribution, please help raise your consideration/requirement/implementation in dev DL for discussion first. It could also help committers to do the review with direction.

**Pull request closed without merging**
