### PR TITLE
EAGLE-125 add LICENSE in eagle-external

### PR DESCRIPTION
**Pull request by qinzhaokun**
https://issues.apache.org/jira/browse/EAGLE-125

### CODE REVIEW

**Comment by pmujumdar** [comment]
@qinzhaokun Looks fine to me. A couple of minor comments/suggestions
AUTHORS.md - The License header is not in the .md comment format. Other .md files look fine.
.git* - It should be okay to add the git files to ignore. I believe the RAT default ignore git specific files, if not the it can be explicitly added to exclude list.

**Comment by haoch** [comment]
Thanks @pmujumdar for review, @qinzhaokun could you please help fix the `AUTHORS.md ` then we could merge the PR into master?

**Comment by qinzhaokun** [comment]
Sorry to make that mistake. Thank @pmujumdar , I have updated AUTHOR.md, @haoch can you help to review this PR?

**Comment by haoch** [comment]
LGTM 

:+1:

**Comment by haoch** [comment]
@qinzhaokun looks good for me, will merge and thanks for the contribution.

**Pull request closed without merging**
