### PR TITLE
Added RM Policy and GC Policies in Resource

### PR DESCRIPTION
**Pull request by senthilec566**

### CODE REVIEW

**Comment by senthilec566** [comment]
@qingwen220  Repaced dataSource with application field.

**Comment by RalphSu** [comment]
Looks good to me.
+1
@qingwen220  please help review as well.

**Comment by senthilec566** [comment]
@RalphSu  @qingwen220  , Can we merge this into master if its not require any more change in script ?

**Comment by qingwen220** [comment]
@senthilec566  I saw the jenkins build failed. Could you please check the details and make sure the merge won't break down the code compilation

**Comment by qingwen220** [comment]
LGTM +1

**Comment by senthilec566** [comment]
Looks like One TestCase Failed 

Results :

Failed tests: 
  TestStrEqualsIgnoreCase(org.apache.eagle.alert.siddhi.TestSiddhiEngine)

**Comment by qingwen220** [comment]
I found it and run it in my local environment, and it's OK! Could you check it as well? If this is caused by jenkins, we will report this bug to Michael. Thanks

**Comment by qingwen220** [comment]
Hi @senthilec566 

Michael have checked with it, and this problem may be caused by Jenkins's instability. You can do a little bit of modifications to this pr, and confirm it again.

**Pull request closed without merging**
